Repository ehk9000/Palette-Picker-API, pull requests merged in 2019-07, with the labels that each got.

#9 Migration setup
  db/migrations/20190701144834_initial.js
  knexfile.js
  server.js
Labels: good first issue

#16 Delete methods
  app.js
Labels: good first issue

#18 Testing
  app.js
  app.test.js
Labels: bug, enhancement, good first issue, help wanted

#20 Added Procfile and deployed to Heroku
  Procfile
Labels: good first issue

#21 WIP: Delete Endpoint tests
  app.test.js
Labels: bug, help wanted

#27 Create project query to filter by name
  app.js
Labels: enhancement, good first issue
